// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Collection struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Picture     string     `json:"picture"`
	Products    []*Product `json:"products"`
}

type Discount struct {
	ID             string  `json:"id"`
	ProductID      string  `json:"productId"`
	NewPrice       float64 `json:"newPrice"`
	Style          string  `json:"style"`
	ExpirationDate string  `json:"ExpirationDate"`
}

type Mutation struct {
}

type NewCollection struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Picture     string    `json:"picture"`
	ProductIds  []*string `json:"productIds"`
}

type NewDiscount struct {
	ProductID      string  `json:"productId"`
	NewPrice       float64 `json:"newPrice"`
	Style          string  `json:"style"`
	ExpirationDate string  `json:"ExpirationDate"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	IsActive    bool    `json:"isActive"`
	Count       int     `json:"count"`
	Picture     string  `json:"picture"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Product struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Price       float64     `json:"price"`
	IsActive    bool        `json:"isActive"`
	Count       int         `json:"count"`
	Picture     string      `json:"picture"`
	Discounts   []*Discount `json:"discounts"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
