// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Advert struct {
	ExpirationDate string     `json:"expirationDate"`
	Text           string     `json:"text"`
	Style          string     `json:"style"`
	Products       []*Product `json:"products"`
}

type Category struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	ParentID    string     `json:"parentId"`
	Picture     string     `json:"picture"`
	Products    []*Product `json:"products,omitempty"`
}

type Collection struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Picture     string     `json:"picture"`
	Products    []*Product `json:"products"`
}

type Discount struct {
	ID             string  `json:"id"`
	ProductID      string  `json:"productId"`
	NewPrice       float64 `json:"newPrice"`
	Style          string  `json:"style"`
	ExpirationDate string  `json:"ExpirationDate"`
}

type Mutation struct {
}

type NewAdvert struct {
	ExpirationDate string    `json:"expirationDate"`
	Text           string    `json:"text"`
	Style          string    `json:"style"`
	ProductIds     []*string `json:"productIds"`
}

type NewCategory struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ParentID    *string `json:"parentId,omitempty"`
	Picture     string  `json:"picture"`
}

type NewCollection struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Picture     string    `json:"picture"`
	ProductIds  []*string `json:"productIds"`
}

type NewDiscount struct {
	ProductID      string  `json:"productId"`
	NewPrice       float64 `json:"newPrice"`
	Style          string  `json:"style"`
	ExpirationDate string  `json:"ExpirationDate"`
}

type NewProduct struct {
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Price        float64   `json:"price"`
	IsActive     bool      `json:"isActive"`
	Count        int       `json:"count"`
	Picture      string    `json:"picture"`
	CategoriesID []*string `json:"categoriesId,omitempty"`
}

type NewProductMedia struct {
	ProductID string `json:"productId"`
	File      string `json:"file"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Product struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Price       float64     `json:"price"`
	IsActive    bool        `json:"isActive"`
	Count       int         `json:"count"`
	Picture     string      `json:"picture"`
	Discounts   []*Discount `json:"discounts"`
}

type ProductMedia struct {
	Product *Product `json:"product"`
	File    string   `json:"file"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
