// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Advert struct {
	ID             string     `json:"id"`
	ExpirationDate string     `json:"expirationDate"`
	AdvertText     string     `json:"advertText"`
	Style          string     `json:"style"`
	Products       []*Product `json:"products,omitempty"`
}

type Collection struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Picture     string     `json:"picture"`
	Products    []*Product `json:"products,omitempty"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Product struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Price       float64       `json:"price"`
	IsActive    bool          `json:"isActive"`
	Count       int           `json:"count"`
	Picture     string        `json:"picture"`
	Collections []*Collection `json:"collections,omitempty"`
	Adverts     []*Advert     `json:"adverts,omitempty"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
